// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.13.0
// source: cuckoofilter/cuckoofilter.proto

package cuckoofilter

import (
	empty "github.com/golang/protobuf/ptypes/empty"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *Status) Reset() {
	*x = Status{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cuckoofilter_cuckoofilter_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_cuckoofilter_cuckoofilter_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_cuckoofilter_cuckoofilter_proto_rawDescGZIP(), []int{0}
}

func (x *Status) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Status) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type CreateFilterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FilterName string `protobuf:"bytes,1,opt,name=filter_name,json=filterName,proto3" json:"filter_name,omitempty"`
	Capacity   uint64 `protobuf:"varint,2,opt,name=capacity,proto3" json:"capacity,omitempty"`
}

func (x *CreateFilterRequest) Reset() {
	*x = CreateFilterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cuckoofilter_cuckoofilter_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateFilterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFilterRequest) ProtoMessage() {}

func (x *CreateFilterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cuckoofilter_cuckoofilter_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFilterRequest.ProtoReflect.Descriptor instead.
func (*CreateFilterRequest) Descriptor() ([]byte, []int) {
	return file_cuckoofilter_cuckoofilter_proto_rawDescGZIP(), []int{1}
}

func (x *CreateFilterRequest) GetFilterName() string {
	if x != nil {
		return x.FilterName
	}
	return ""
}

func (x *CreateFilterRequest) GetCapacity() uint64 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

type CreateFilterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *CreateFilterResponse) Reset() {
	*x = CreateFilterResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cuckoofilter_cuckoofilter_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateFilterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFilterResponse) ProtoMessage() {}

func (x *CreateFilterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cuckoofilter_cuckoofilter_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFilterResponse.ProtoReflect.Descriptor instead.
func (*CreateFilterResponse) Descriptor() ([]byte, []int) {
	return file_cuckoofilter_cuckoofilter_proto_rawDescGZIP(), []int{2}
}

func (x *CreateFilterResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type DeleteFilterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FilterName string `protobuf:"bytes,1,opt,name=filter_name,json=filterName,proto3" json:"filter_name,omitempty"`
}

func (x *DeleteFilterRequest) Reset() {
	*x = DeleteFilterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cuckoofilter_cuckoofilter_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteFilterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFilterRequest) ProtoMessage() {}

func (x *DeleteFilterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cuckoofilter_cuckoofilter_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFilterRequest.ProtoReflect.Descriptor instead.
func (*DeleteFilterRequest) Descriptor() ([]byte, []int) {
	return file_cuckoofilter_cuckoofilter_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteFilterRequest) GetFilterName() string {
	if x != nil {
		return x.FilterName
	}
	return ""
}

type DeleteFilterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *DeleteFilterResponse) Reset() {
	*x = DeleteFilterResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cuckoofilter_cuckoofilter_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteFilterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFilterResponse) ProtoMessage() {}

func (x *DeleteFilterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cuckoofilter_cuckoofilter_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFilterResponse.ProtoReflect.Descriptor instead.
func (*DeleteFilterResponse) Descriptor() ([]byte, []int) {
	return file_cuckoofilter_cuckoofilter_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteFilterResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type ListFiltersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Filters []string `protobuf:"bytes,2,rep,name=filters,proto3" json:"filters,omitempty"`
}

func (x *ListFiltersResponse) Reset() {
	*x = ListFiltersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cuckoofilter_cuckoofilter_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListFiltersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFiltersResponse) ProtoMessage() {}

func (x *ListFiltersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cuckoofilter_cuckoofilter_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFiltersResponse.ProtoReflect.Descriptor instead.
func (*ListFiltersResponse) Descriptor() ([]byte, []int) {
	return file_cuckoofilter_cuckoofilter_proto_rawDescGZIP(), []int{5}
}

func (x *ListFiltersResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *ListFiltersResponse) GetFilters() []string {
	if x != nil {
		return x.Filters
	}
	return nil
}

type InsertElementRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FilterName string `protobuf:"bytes,1,opt,name=filter_name,json=filterName,proto3" json:"filter_name,omitempty"`
	Element    string `protobuf:"bytes,2,opt,name=element,proto3" json:"element,omitempty"`
}

func (x *InsertElementRequest) Reset() {
	*x = InsertElementRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cuckoofilter_cuckoofilter_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InsertElementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertElementRequest) ProtoMessage() {}

func (x *InsertElementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cuckoofilter_cuckoofilter_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertElementRequest.ProtoReflect.Descriptor instead.
func (*InsertElementRequest) Descriptor() ([]byte, []int) {
	return file_cuckoofilter_cuckoofilter_proto_rawDescGZIP(), []int{6}
}

func (x *InsertElementRequest) GetFilterName() string {
	if x != nil {
		return x.FilterName
	}
	return ""
}

func (x *InsertElementRequest) GetElement() string {
	if x != nil {
		return x.Element
	}
	return ""
}

type InsertElementResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *InsertElementResponse) Reset() {
	*x = InsertElementResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cuckoofilter_cuckoofilter_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InsertElementResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertElementResponse) ProtoMessage() {}

func (x *InsertElementResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cuckoofilter_cuckoofilter_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertElementResponse.ProtoReflect.Descriptor instead.
func (*InsertElementResponse) Descriptor() ([]byte, []int) {
	return file_cuckoofilter_cuckoofilter_proto_rawDescGZIP(), []int{7}
}

func (x *InsertElementResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type InsertElementsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FilterName string   `protobuf:"bytes,1,opt,name=filter_name,json=filterName,proto3" json:"filter_name,omitempty"`
	Elements   []string `protobuf:"bytes,2,rep,name=elements,proto3" json:"elements,omitempty"`
}

func (x *InsertElementsRequest) Reset() {
	*x = InsertElementsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cuckoofilter_cuckoofilter_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InsertElementsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertElementsRequest) ProtoMessage() {}

func (x *InsertElementsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cuckoofilter_cuckoofilter_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertElementsRequest.ProtoReflect.Descriptor instead.
func (*InsertElementsRequest) Descriptor() ([]byte, []int) {
	return file_cuckoofilter_cuckoofilter_proto_rawDescGZIP(), []int{8}
}

func (x *InsertElementsRequest) GetFilterName() string {
	if x != nil {
		return x.FilterName
	}
	return ""
}

func (x *InsertElementsRequest) GetElements() []string {
	if x != nil {
		return x.Elements
	}
	return nil
}

type InsertElementsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status         *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	FailedElements []string `protobuf:"bytes,2,rep,name=failed_elements,json=failedElements,proto3" json:"failed_elements,omitempty"`
}

func (x *InsertElementsResponse) Reset() {
	*x = InsertElementsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cuckoofilter_cuckoofilter_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InsertElementsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertElementsResponse) ProtoMessage() {}

func (x *InsertElementsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cuckoofilter_cuckoofilter_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertElementsResponse.ProtoReflect.Descriptor instead.
func (*InsertElementsResponse) Descriptor() ([]byte, []int) {
	return file_cuckoofilter_cuckoofilter_proto_rawDescGZIP(), []int{9}
}

func (x *InsertElementsResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *InsertElementsResponse) GetFailedElements() []string {
	if x != nil {
		return x.FailedElements
	}
	return nil
}

type DeleteElementRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FilterName string `protobuf:"bytes,1,opt,name=filter_name,json=filterName,proto3" json:"filter_name,omitempty"`
	Element    string `protobuf:"bytes,2,opt,name=element,proto3" json:"element,omitempty"`
}

func (x *DeleteElementRequest) Reset() {
	*x = DeleteElementRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cuckoofilter_cuckoofilter_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteElementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteElementRequest) ProtoMessage() {}

func (x *DeleteElementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cuckoofilter_cuckoofilter_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteElementRequest.ProtoReflect.Descriptor instead.
func (*DeleteElementRequest) Descriptor() ([]byte, []int) {
	return file_cuckoofilter_cuckoofilter_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteElementRequest) GetFilterName() string {
	if x != nil {
		return x.FilterName
	}
	return ""
}

func (x *DeleteElementRequest) GetElement() string {
	if x != nil {
		return x.Element
	}
	return ""
}

type DeleteElementResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *DeleteElementResponse) Reset() {
	*x = DeleteElementResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cuckoofilter_cuckoofilter_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteElementResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteElementResponse) ProtoMessage() {}

func (x *DeleteElementResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cuckoofilter_cuckoofilter_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteElementResponse.ProtoReflect.Descriptor instead.
func (*DeleteElementResponse) Descriptor() ([]byte, []int) {
	return file_cuckoofilter_cuckoofilter_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteElementResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type CountElementsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FilterName string `protobuf:"bytes,1,opt,name=filter_name,json=filterName,proto3" json:"filter_name,omitempty"`
}

func (x *CountElementsRequest) Reset() {
	*x = CountElementsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cuckoofilter_cuckoofilter_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CountElementsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountElementsRequest) ProtoMessage() {}

func (x *CountElementsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cuckoofilter_cuckoofilter_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountElementsRequest.ProtoReflect.Descriptor instead.
func (*CountElementsRequest) Descriptor() ([]byte, []int) {
	return file_cuckoofilter_cuckoofilter_proto_rawDescGZIP(), []int{12}
}

func (x *CountElementsRequest) GetFilterName() string {
	if x != nil {
		return x.FilterName
	}
	return ""
}

type CountElementsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Len    uint64  `protobuf:"varint,2,opt,name=len,proto3" json:"len,omitempty"`
}

func (x *CountElementsResponse) Reset() {
	*x = CountElementsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cuckoofilter_cuckoofilter_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CountElementsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountElementsResponse) ProtoMessage() {}

func (x *CountElementsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cuckoofilter_cuckoofilter_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountElementsResponse.ProtoReflect.Descriptor instead.
func (*CountElementsResponse) Descriptor() ([]byte, []int) {
	return file_cuckoofilter_cuckoofilter_proto_rawDescGZIP(), []int{13}
}

func (x *CountElementsResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *CountElementsResponse) GetLen() uint64 {
	if x != nil {
		return x.Len
	}
	return 0
}

type ResetFilterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FilterName string `protobuf:"bytes,1,opt,name=filter_name,json=filterName,proto3" json:"filter_name,omitempty"`
}

func (x *ResetFilterRequest) Reset() {
	*x = ResetFilterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cuckoofilter_cuckoofilter_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResetFilterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetFilterRequest) ProtoMessage() {}

func (x *ResetFilterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cuckoofilter_cuckoofilter_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetFilterRequest.ProtoReflect.Descriptor instead.
func (*ResetFilterRequest) Descriptor() ([]byte, []int) {
	return file_cuckoofilter_cuckoofilter_proto_rawDescGZIP(), []int{14}
}

func (x *ResetFilterRequest) GetFilterName() string {
	if x != nil {
		return x.FilterName
	}
	return ""
}

type ResetFilterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *ResetFilterResponse) Reset() {
	*x = ResetFilterResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cuckoofilter_cuckoofilter_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResetFilterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetFilterResponse) ProtoMessage() {}

func (x *ResetFilterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cuckoofilter_cuckoofilter_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetFilterResponse.ProtoReflect.Descriptor instead.
func (*ResetFilterResponse) Descriptor() ([]byte, []int) {
	return file_cuckoofilter_cuckoofilter_proto_rawDescGZIP(), []int{15}
}

func (x *ResetFilterResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type LookupElementRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FilterName string `protobuf:"bytes,1,opt,name=filter_name,json=filterName,proto3" json:"filter_name,omitempty"`
	Element    string `protobuf:"bytes,2,opt,name=element,proto3" json:"element,omitempty"`
}

func (x *LookupElementRequest) Reset() {
	*x = LookupElementRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cuckoofilter_cuckoofilter_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LookupElementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupElementRequest) ProtoMessage() {}

func (x *LookupElementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cuckoofilter_cuckoofilter_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupElementRequest.ProtoReflect.Descriptor instead.
func (*LookupElementRequest) Descriptor() ([]byte, []int) {
	return file_cuckoofilter_cuckoofilter_proto_rawDescGZIP(), []int{16}
}

func (x *LookupElementRequest) GetFilterName() string {
	if x != nil {
		return x.FilterName
	}
	return ""
}

func (x *LookupElementRequest) GetElement() string {
	if x != nil {
		return x.Element
	}
	return ""
}

type LookupElementResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *LookupElementResponse) Reset() {
	*x = LookupElementResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cuckoofilter_cuckoofilter_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LookupElementResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupElementResponse) ProtoMessage() {}

func (x *LookupElementResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cuckoofilter_cuckoofilter_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupElementResponse.ProtoReflect.Descriptor instead.
func (*LookupElementResponse) Descriptor() ([]byte, []int) {
	return file_cuckoofilter_cuckoofilter_proto_rawDescGZIP(), []int{17}
}

func (x *LookupElementResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type LookupElementsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FilterName string   `protobuf:"bytes,1,opt,name=filter_name,json=filterName,proto3" json:"filter_name,omitempty"`
	Elements   []string `protobuf:"bytes,2,rep,name=elements,proto3" json:"elements,omitempty"`
}

func (x *LookupElementsRequest) Reset() {
	*x = LookupElementsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cuckoofilter_cuckoofilter_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LookupElementsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupElementsRequest) ProtoMessage() {}

func (x *LookupElementsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cuckoofilter_cuckoofilter_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupElementsRequest.ProtoReflect.Descriptor instead.
func (*LookupElementsRequest) Descriptor() ([]byte, []int) {
	return file_cuckoofilter_cuckoofilter_proto_rawDescGZIP(), []int{18}
}

func (x *LookupElementsRequest) GetFilterName() string {
	if x != nil {
		return x.FilterName
	}
	return ""
}

func (x *LookupElementsRequest) GetElements() []string {
	if x != nil {
		return x.Elements
	}
	return nil
}

type LookupElementsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status   *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Elements []string `protobuf:"bytes,2,rep,name=elements,proto3" json:"elements,omitempty"`
}

func (x *LookupElementsResponse) Reset() {
	*x = LookupElementsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cuckoofilter_cuckoofilter_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LookupElementsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupElementsResponse) ProtoMessage() {}

func (x *LookupElementsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cuckoofilter_cuckoofilter_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupElementsResponse.ProtoReflect.Descriptor instead.
func (*LookupElementsResponse) Descriptor() ([]byte, []int) {
	return file_cuckoofilter_cuckoofilter_proto_rawDescGZIP(), []int{19}
}

func (x *LookupElementsResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *LookupElementsResponse) GetElements() []string {
	if x != nil {
		return x.Elements
	}
	return nil
}

type LookupElementsStreamRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FilterName string `protobuf:"bytes,1,opt,name=filter_name,json=filterName,proto3" json:"filter_name,omitempty"`
	Element    string `protobuf:"bytes,2,opt,name=element,proto3" json:"element,omitempty"`
}

func (x *LookupElementsStreamRequest) Reset() {
	*x = LookupElementsStreamRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cuckoofilter_cuckoofilter_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LookupElementsStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupElementsStreamRequest) ProtoMessage() {}

func (x *LookupElementsStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cuckoofilter_cuckoofilter_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupElementsStreamRequest.ProtoReflect.Descriptor instead.
func (*LookupElementsStreamRequest) Descriptor() ([]byte, []int) {
	return file_cuckoofilter_cuckoofilter_proto_rawDescGZIP(), []int{20}
}

func (x *LookupElementsStreamRequest) GetFilterName() string {
	if x != nil {
		return x.FilterName
	}
	return ""
}

func (x *LookupElementsStreamRequest) GetElement() string {
	if x != nil {
		return x.Element
	}
	return ""
}

type LookupElementsStreamResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Element string `protobuf:"bytes,2,opt,name=element,proto3" json:"element,omitempty"`
}

func (x *LookupElementsStreamResponse) Reset() {
	*x = LookupElementsStreamResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cuckoofilter_cuckoofilter_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LookupElementsStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupElementsStreamResponse) ProtoMessage() {}

func (x *LookupElementsStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cuckoofilter_cuckoofilter_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupElementsStreamResponse.ProtoReflect.Descriptor instead.
func (*LookupElementsStreamResponse) Descriptor() ([]byte, []int) {
	return file_cuckoofilter_cuckoofilter_proto_rawDescGZIP(), []int{21}
}

func (x *LookupElementsStreamResponse) GetElement() string {
	if x != nil {
		return x.Element
	}
	return ""
}

var File_cuckoofilter_cuckoofilter_proto protoreflect.FileDescriptor

var file_cuckoofilter_cuckoofilter_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x63, 0x75, 0x63, 0x6b, 0x6f, 0x6f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x2f, 0x63,
	0x75, 0x63, 0x6b, 0x6f, 0x6f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0c, 0x63, 0x75, 0x63, 0x6b, 0x6f, 0x6f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x1a,
	0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2e, 0x0a, 0x06,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73,
	0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x52, 0x0a, 0x13,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x63, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79,
	0x22, 0x44, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x63, 0x75, 0x63, 0x6b, 0x6f,
	0x6f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x36, 0x0a, 0x13, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a,
	0x0b, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x44,
	0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x63, 0x75, 0x63, 0x6b, 0x6f, 0x6f, 0x66,
	0x69, 0x6c, 0x74, 0x65, 0x72, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x22, 0x5d, 0x0a, 0x13, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x69, 0x6c, 0x74,
	0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x63, 0x75,
	0x63, 0x6b, 0x6f, 0x6f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x66, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x66, 0x69, 0x6c, 0x74,
	0x65, 0x72, 0x73, 0x22, 0x51, 0x0a, 0x14, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x45, 0x6c, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x66,
	0x69, 0x6c, 0x74, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65,
	0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x45, 0x0a, 0x15, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74,
	0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x2c, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x14, 0x2e, 0x63, 0x75, 0x63, 0x6b, 0x6f, 0x6f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x2e, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x54, 0x0a,
	0x15, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x66, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x6c, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x65, 0x6c, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x73, 0x22, 0x6f, 0x0a, 0x16, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x45, 0x6c, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e,
	0x63, 0x75, 0x63, 0x6b, 0x6f, 0x6f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x2e, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x27, 0x0a, 0x0f, 0x66,
	0x61, 0x69, 0x6c, 0x65, 0x64, 0x5f, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x0e, 0x66, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x45, 0x6c, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x73, 0x22, 0x51, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x45, 0x6c,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b,
	0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x45, 0x0a, 0x15, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x2c, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x63, 0x75, 0x63, 0x6b, 0x6f, 0x6f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x2e,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x37,
	0x0a, 0x14, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x66, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x57, 0x0a, 0x15, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x2c, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x63, 0x75, 0x63, 0x6b, 0x6f, 0x6f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x2e,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x10,
	0x0a, 0x03, 0x6c, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x6c, 0x65, 0x6e,
	0x22, 0x35, 0x0a, 0x12, 0x52, 0x65, 0x73, 0x65, 0x74, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x66, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x43, 0x0a, 0x13, 0x52, 0x65, 0x73, 0x65, 0x74,
	0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14,
	0x2e, 0x63, 0x75, 0x63, 0x6b, 0x6f, 0x6f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x2e, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x51, 0x0a, 0x14,
	0x4c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x66, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x22,
	0x45, 0x0a, 0x15, 0x4c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x63, 0x75, 0x63, 0x6b, 0x6f,
	0x6f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x54, 0x0a, 0x15, 0x4c, 0x6f, 0x6f, 0x6b, 0x75, 0x70,
	0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1f, 0x0a, 0x0b, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x08, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x62, 0x0a, 0x16,
	0x4c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x63, 0x75, 0x63, 0x6b, 0x6f, 0x6f, 0x66,
	0x69, 0x6c, 0x74, 0x65, 0x72, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73,
	0x22, 0x58, 0x0a, 0x1b, 0x4c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x73, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1f, 0x0a, 0x0b, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x38, 0x0a, 0x1c, 0x4c, 0x6f,
	0x6f, 0x6b, 0x75, 0x70, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x53, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6c,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x6c, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x32, 0x85, 0x08, 0x0a, 0x0c, 0x43, 0x75, 0x63, 0x6b, 0x6f, 0x6f, 0x46,
	0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x57, 0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46,
	0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x21, 0x2e, 0x63, 0x75, 0x63, 0x6b, 0x6f, 0x6f, 0x66, 0x69,
	0x6c, 0x74, 0x65, 0x72, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x63, 0x75, 0x63, 0x6b, 0x6f,
	0x6f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x69,
	0x6c, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x57,
	0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x21,
	0x2e, 0x63, 0x75, 0x63, 0x6b, 0x6f, 0x6f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x2e, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x22, 0x2e, 0x63, 0x75, 0x63, 0x6b, 0x6f, 0x6f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72,
	0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4a, 0x0a, 0x0b, 0x4c, 0x69, 0x73, 0x74, 0x46,
	0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x21,
	0x2e, 0x63, 0x75, 0x63, 0x6b, 0x6f, 0x6f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x5a, 0x0a, 0x0d, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x45, 0x6c, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x12, 0x22, 0x2e, 0x63, 0x75, 0x63, 0x6b, 0x6f, 0x6f, 0x66, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x2e, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x63, 0x75, 0x63, 0x6b, 0x6f,
	0x6f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x2e, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x45, 0x6c,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x5d, 0x0a, 0x0e, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74,
	0x73, 0x12, 0x23, 0x2e, 0x63, 0x75, 0x63, 0x6b, 0x6f, 0x6f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72,
	0x2e, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x63, 0x75, 0x63, 0x6b, 0x6f, 0x6f, 0x66,
	0x69, 0x6c, 0x74, 0x65, 0x72, 0x2e, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x45, 0x6c, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5a,
	0x0a, 0x0d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12,
	0x22, 0x2e, 0x63, 0x75, 0x63, 0x6b, 0x6f, 0x6f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x2e, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x63, 0x75, 0x63, 0x6b, 0x6f, 0x6f, 0x66, 0x69, 0x6c, 0x74,
	0x65, 0x72, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5a, 0x0a, 0x0d, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x22, 0x2e, 0x63, 0x75,
	0x63, 0x6b, 0x6f, 0x6f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x2e, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x23, 0x2e, 0x63, 0x75, 0x63, 0x6b, 0x6f, 0x6f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x2e, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x54, 0x0a, 0x0b, 0x52, 0x65, 0x73, 0x65, 0x74, 0x46,
	0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x20, 0x2e, 0x63, 0x75, 0x63, 0x6b, 0x6f, 0x6f, 0x66, 0x69,
	0x6c, 0x74, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x73, 0x65, 0x74, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x63, 0x75, 0x63, 0x6b, 0x6f, 0x6f,
	0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x73, 0x65, 0x74, 0x46, 0x69, 0x6c, 0x74,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5a, 0x0a, 0x0d,
	0x4c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x22, 0x2e,
	0x63, 0x75, 0x63, 0x6b, 0x6f, 0x6f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x2e, 0x4c, 0x6f, 0x6f,
	0x6b, 0x75, 0x70, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x23, 0x2e, 0x63, 0x75, 0x63, 0x6b, 0x6f, 0x6f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72,
	0x2e, 0x4c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5d, 0x0a, 0x0e, 0x4c, 0x6f, 0x6f, 0x6b,
	0x75, 0x70, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x23, 0x2e, 0x63, 0x75, 0x63,
	0x6b, 0x6f, 0x6f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x2e, 0x4c, 0x6f, 0x6f, 0x6b, 0x75, 0x70,
	0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x24, 0x2e, 0x63, 0x75, 0x63, 0x6b, 0x6f, 0x6f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x2e, 0x4c,
	0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x73, 0x0a, 0x14, 0x4c, 0x6f, 0x6f, 0x6b, 0x75,
	0x70, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12,
	0x29, 0x2e, 0x63, 0x75, 0x63, 0x6b, 0x6f, 0x6f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x2e, 0x4c,
	0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x53, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2a, 0x2e, 0x63, 0x75, 0x63,
	0x6b, 0x6f, 0x6f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x2e, 0x4c, 0x6f, 0x6f, 0x6b, 0x75, 0x70,
	0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x40, 0x0a, 0x0c,
	0x63, 0x75, 0x63, 0x6b, 0x6f, 0x6f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x50, 0x01, 0x5a, 0x2e,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x75, 0x6f, 0x62, 0x69,
	0x6e, 0x71, 0x69, 0x75, 0x2f, 0x63, 0x75, 0x63, 0x6b, 0x6f, 0x6f, 0x66, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x2f, 0x63, 0x75, 0x63, 0x6b, 0x6f, 0x6f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cuckoofilter_cuckoofilter_proto_rawDescOnce sync.Once
	file_cuckoofilter_cuckoofilter_proto_rawDescData = file_cuckoofilter_cuckoofilter_proto_rawDesc
)

func file_cuckoofilter_cuckoofilter_proto_rawDescGZIP() []byte {
	file_cuckoofilter_cuckoofilter_proto_rawDescOnce.Do(func() {
		file_cuckoofilter_cuckoofilter_proto_rawDescData = protoimpl.X.CompressGZIP(file_cuckoofilter_cuckoofilter_proto_rawDescData)
	})
	return file_cuckoofilter_cuckoofilter_proto_rawDescData
}

var file_cuckoofilter_cuckoofilter_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_cuckoofilter_cuckoofilter_proto_goTypes = []interface{}{
	(*Status)(nil),                       // 0: cuckoofilter.Status
	(*CreateFilterRequest)(nil),          // 1: cuckoofilter.CreateFilterRequest
	(*CreateFilterResponse)(nil),         // 2: cuckoofilter.CreateFilterResponse
	(*DeleteFilterRequest)(nil),          // 3: cuckoofilter.DeleteFilterRequest
	(*DeleteFilterResponse)(nil),         // 4: cuckoofilter.DeleteFilterResponse
	(*ListFiltersResponse)(nil),          // 5: cuckoofilter.ListFiltersResponse
	(*InsertElementRequest)(nil),         // 6: cuckoofilter.InsertElementRequest
	(*InsertElementResponse)(nil),        // 7: cuckoofilter.InsertElementResponse
	(*InsertElementsRequest)(nil),        // 8: cuckoofilter.InsertElementsRequest
	(*InsertElementsResponse)(nil),       // 9: cuckoofilter.InsertElementsResponse
	(*DeleteElementRequest)(nil),         // 10: cuckoofilter.DeleteElementRequest
	(*DeleteElementResponse)(nil),        // 11: cuckoofilter.DeleteElementResponse
	(*CountElementsRequest)(nil),         // 12: cuckoofilter.CountElementsRequest
	(*CountElementsResponse)(nil),        // 13: cuckoofilter.CountElementsResponse
	(*ResetFilterRequest)(nil),           // 14: cuckoofilter.ResetFilterRequest
	(*ResetFilterResponse)(nil),          // 15: cuckoofilter.ResetFilterResponse
	(*LookupElementRequest)(nil),         // 16: cuckoofilter.LookupElementRequest
	(*LookupElementResponse)(nil),        // 17: cuckoofilter.LookupElementResponse
	(*LookupElementsRequest)(nil),        // 18: cuckoofilter.LookupElementsRequest
	(*LookupElementsResponse)(nil),       // 19: cuckoofilter.LookupElementsResponse
	(*LookupElementsStreamRequest)(nil),  // 20: cuckoofilter.LookupElementsStreamRequest
	(*LookupElementsStreamResponse)(nil), // 21: cuckoofilter.LookupElementsStreamResponse
	(*empty.Empty)(nil),                  // 22: google.protobuf.Empty
}
var file_cuckoofilter_cuckoofilter_proto_depIdxs = []int32{
	0,  // 0: cuckoofilter.CreateFilterResponse.status:type_name -> cuckoofilter.Status
	0,  // 1: cuckoofilter.DeleteFilterResponse.status:type_name -> cuckoofilter.Status
	0,  // 2: cuckoofilter.ListFiltersResponse.status:type_name -> cuckoofilter.Status
	0,  // 3: cuckoofilter.InsertElementResponse.status:type_name -> cuckoofilter.Status
	0,  // 4: cuckoofilter.InsertElementsResponse.status:type_name -> cuckoofilter.Status
	0,  // 5: cuckoofilter.DeleteElementResponse.status:type_name -> cuckoofilter.Status
	0,  // 6: cuckoofilter.CountElementsResponse.status:type_name -> cuckoofilter.Status
	0,  // 7: cuckoofilter.ResetFilterResponse.status:type_name -> cuckoofilter.Status
	0,  // 8: cuckoofilter.LookupElementResponse.status:type_name -> cuckoofilter.Status
	0,  // 9: cuckoofilter.LookupElementsResponse.status:type_name -> cuckoofilter.Status
	1,  // 10: cuckoofilter.CuckooFilter.CreateFilter:input_type -> cuckoofilter.CreateFilterRequest
	3,  // 11: cuckoofilter.CuckooFilter.DeleteFilter:input_type -> cuckoofilter.DeleteFilterRequest
	22, // 12: cuckoofilter.CuckooFilter.ListFilters:input_type -> google.protobuf.Empty
	6,  // 13: cuckoofilter.CuckooFilter.InsertElement:input_type -> cuckoofilter.InsertElementRequest
	8,  // 14: cuckoofilter.CuckooFilter.InsertElements:input_type -> cuckoofilter.InsertElementsRequest
	10, // 15: cuckoofilter.CuckooFilter.DeleteElement:input_type -> cuckoofilter.DeleteElementRequest
	12, // 16: cuckoofilter.CuckooFilter.CountElements:input_type -> cuckoofilter.CountElementsRequest
	14, // 17: cuckoofilter.CuckooFilter.ResetFilter:input_type -> cuckoofilter.ResetFilterRequest
	16, // 18: cuckoofilter.CuckooFilter.LookupElement:input_type -> cuckoofilter.LookupElementRequest
	18, // 19: cuckoofilter.CuckooFilter.LookupElements:input_type -> cuckoofilter.LookupElementsRequest
	20, // 20: cuckoofilter.CuckooFilter.LookupElementsStream:input_type -> cuckoofilter.LookupElementsStreamRequest
	2,  // 21: cuckoofilter.CuckooFilter.CreateFilter:output_type -> cuckoofilter.CreateFilterResponse
	4,  // 22: cuckoofilter.CuckooFilter.DeleteFilter:output_type -> cuckoofilter.DeleteFilterResponse
	5,  // 23: cuckoofilter.CuckooFilter.ListFilters:output_type -> cuckoofilter.ListFiltersResponse
	7,  // 24: cuckoofilter.CuckooFilter.InsertElement:output_type -> cuckoofilter.InsertElementResponse
	9,  // 25: cuckoofilter.CuckooFilter.InsertElements:output_type -> cuckoofilter.InsertElementsResponse
	11, // 26: cuckoofilter.CuckooFilter.DeleteElement:output_type -> cuckoofilter.DeleteElementResponse
	13, // 27: cuckoofilter.CuckooFilter.CountElements:output_type -> cuckoofilter.CountElementsResponse
	15, // 28: cuckoofilter.CuckooFilter.ResetFilter:output_type -> cuckoofilter.ResetFilterResponse
	17, // 29: cuckoofilter.CuckooFilter.LookupElement:output_type -> cuckoofilter.LookupElementResponse
	19, // 30: cuckoofilter.CuckooFilter.LookupElements:output_type -> cuckoofilter.LookupElementsResponse
	21, // 31: cuckoofilter.CuckooFilter.LookupElementsStream:output_type -> cuckoofilter.LookupElementsStreamResponse
	21, // [21:32] is the sub-list for method output_type
	10, // [10:21] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_cuckoofilter_cuckoofilter_proto_init() }
func file_cuckoofilter_cuckoofilter_proto_init() {
	if File_cuckoofilter_cuckoofilter_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cuckoofilter_cuckoofilter_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Status); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cuckoofilter_cuckoofilter_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateFilterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cuckoofilter_cuckoofilter_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateFilterResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cuckoofilter_cuckoofilter_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteFilterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cuckoofilter_cuckoofilter_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteFilterResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cuckoofilter_cuckoofilter_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListFiltersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cuckoofilter_cuckoofilter_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InsertElementRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cuckoofilter_cuckoofilter_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InsertElementResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cuckoofilter_cuckoofilter_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InsertElementsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cuckoofilter_cuckoofilter_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InsertElementsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cuckoofilter_cuckoofilter_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteElementRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cuckoofilter_cuckoofilter_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteElementResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cuckoofilter_cuckoofilter_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CountElementsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cuckoofilter_cuckoofilter_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CountElementsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cuckoofilter_cuckoofilter_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResetFilterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cuckoofilter_cuckoofilter_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResetFilterResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cuckoofilter_cuckoofilter_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LookupElementRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cuckoofilter_cuckoofilter_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LookupElementResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cuckoofilter_cuckoofilter_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LookupElementsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cuckoofilter_cuckoofilter_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LookupElementsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cuckoofilter_cuckoofilter_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LookupElementsStreamRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cuckoofilter_cuckoofilter_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LookupElementsStreamResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cuckoofilter_cuckoofilter_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cuckoofilter_cuckoofilter_proto_goTypes,
		DependencyIndexes: file_cuckoofilter_cuckoofilter_proto_depIdxs,
		MessageInfos:      file_cuckoofilter_cuckoofilter_proto_msgTypes,
	}.Build()
	File_cuckoofilter_cuckoofilter_proto = out.File
	file_cuckoofilter_cuckoofilter_proto_rawDesc = nil
	file_cuckoofilter_cuckoofilter_proto_goTypes = nil
	file_cuckoofilter_cuckoofilter_proto_depIdxs = nil
}
